CHANGELOG.md
Agrega changelog para revisión 2 del release de Julio 2021.
=> Agrega changelog para version 21.07.2

modules/filtros.R, modules/outliers.R
=> refactor: Corrige typo en outliers

R/caja_de_bigotes_agrupador.R, R/comparar_nt_valor_factura.R, R/completar_meses.R, R/descriptiva_timeseries.R, R/episodios_jerarquia.R, R/frecuencias.R, R/frecuencias_dia.R, R/frecuencias_jerarquia.R, R/frecuencias_mes.R, R/identificar_episodios.R, widgets/episodios_jerarquia_server.R
=> refactor: Simplificar funciones largas

manifest.json, renv.lock
=> Actualiza paquetes en renv.lock y manifest

www/style.css
=> Permite ajusta filtros en panatallas pequeñas

R/completar_meses.R
fix: Corrige nombre columna ais_anio en R/completar_meses
=> Corrige ais_anio en completar_meses

modules/nota_tecnica.R
=> Elimina botón de frecuencias en nota tecnica

man/conjunto_datos.md
=> Describe conjunto mínimo de datos

CONTRIBUTING.md
=> fix: Corrige ortografía en CONTRIBUTING.md

R/completar_meses.R
=> Corrige frecuencia con episodios complejos

man/cargar_datos.md, man/nota_tecnica.md, man/seguimiento_contratos.md
=> Documenta uso de techos y pisos en seguimiento

modules/seguimiento.R
=> Corrige error de seleccion de rango fechas erroneo

json_schemas/paquetes.json
=> feat: Adiciona esquema json para paquetes

widgets/episodios_jerarquia_server.R
=> fix: Corrige error al cambiar tablas en jerarquia

CHANGELOG.md, ui.R
Resolves #49
Cambios oficiales entre 21.07.2 y 21.08.1
- feat: Adiciona unidad de conteo a módulo notas técnicas (2021-07-26)
- feat: Compara techos y pisos de una nota técnica (2021-07-23)
- fix: Corrige error al cambiar tablas en jerarquía (2021-07-30)
- fix: Corrige error de con datos vacíos en seguimiento (2021-07-28)
- fix: Corrige error frecuencia con episodios complejos (2021-07-26)
- fix: Corrige typo en mensajes al guardar perfil y notas técnicas (2021-07-22)
- fix: Permite ajusta filtros en pantallas pequeñas (2021-07-22)
- fix: Corrige error donde se suma valor no correspondiente a la nota técnica. (2021-07-21)
=> Cambios necesarios para release 21.08.1

modules/nota_tecnica.R
=> fix: Corrige error con la cración de multiples NTs

modules/nota_tecnica.R
=> Corrige error en nota técnica

R/comparar_nt.R, modules/seguimiento.R
=> Agrega indicadores a nota técnica y simplifica tablas

modules/nota_tecnica.R
=> fix: Corrige creación de perfiles en nota técnica

modules/nota_tecnica.R, modules/seguimiento.R
=> WIP: Adiciona pestaña con gráfica de costo medio

R/outliers_iqr.R, R/outliers_percentil.R
=> fix: Corrige error en outliers con valores NA

renv.lock
=> fix: Cambia repositorios viejos a nuevos

README.md, manifest.json, renv.lock
=> Actualiza README y manifest

modules/filtros.R
=> fix: Muestra variables cuantitativas al agregar filas

man/filtros_opciones.md, modules/filtros.R
=> docs: Documenta modulo filtros - identificación de pacientes

modules/nota_tecnica.R
=> fix: Evita crash de la aplicación al buscar en notas técnicas.

CHANGELOG.md, ui.R
Actualiza versión en ui.R
Resolves #92
=> feat: Release 21.9.1 Armadillo
